export enum LinksTypes {
    LINK_CHANGE_NEW = 'LINK_CHANGE_NEW',
    LINK_CREATE_NEW = 'LINK_CREATE_NEW',
    LINK_INCREMENT_VIEW_COUNT = 'LINK_INCREMENT_VIEW_COUNT',
    LINK_REMOVE = 'LINK_REMOVE'
}
